### ISSUE TITLE
Crash: Memory access out of range when getting a list of values from a rulebook

### ISSUE THREAD

**Issue by curiousdannii** [i7/inform7-bugs#1]
Reported at

- https://intfiction.org/t/crash-memory-access-out-of-range-when-getting-a-list-of-values-from-a-rulebook/50338
- https://intfiction.org/t/i7-6m62-rulebook-producing-a-list-of-numbers/13696

Patch available: https://github.com/i7/extensions/blob/master/Friends%20of%20I7/6M62%20Patches.i7x

**Comment by zedlopez** [comment]
this problem doesn't occur in v10.

**Comment by zedlopez** [comment]
fix has been incorporated in v10.
