### ISSUE TITLE
"Time since" is negative for things that happened later yesterday

### ISSUE THREAD

**Issue by angstsmurf** [i7/inform7-bugs#15]
The documentation (§10.3. Using the Scene index) recommends this way to make a scene last 3 turns:

```
Train Stop ends when the time since Train Stop began is 3 minutes.
```
But if the scene began less than four minutes before midnight, this means it will never end!

The `time of day` variable in Inform 7 is the current game time in minutes since midnight. At midnight, it is 0. So if the Train Stop scene occurs a minute before midnight, it happens at time of day 1439. When time of day passes 1439, it goes back to 0, assuming the standard pace of 1 minute per turn. Then time since 1439 (when Train Stop began) will be -1439 minutes. The next turn it will be -1438 minutes. One minute before the next midnight, `the time since Train Stop began` will be 0. It will never be 3.

EDIT:
[Fix courtesy of otistdog:](https://intfiction.org/t/inform-7-time-bug/52464/2)

```
Include
(-

! ==== ==== ==== ==== ==== ==== ==== ==== ==== ====
! Time.i6t: Scene Questions (modified)
! ==== ==== ==== ==== ==== ==== ==== ==== ==== ====

[ SceneUtility sc task;
    if (sc <= 0) return 0;
    if (task == 1 or 2) {
	    if (scene_endings-->(sc-1) == 0) return RunTimeProblem(RTP_SCENEHASNTSTARTED, sc);
    } else {
	    if (scene_endings-->(sc-1) <= 1) return RunTimeProblem(RTP_SCENEHASNTENDED, sc);
    }
    switch (task) {
	    1:
		    if (the_time >= scene_started-->(sc-1)) ! current time is the same or later than scene starting time, so no change
			    return (the_time - scene_started-->(sc-1))%(TWENTY_FOUR_HOURS);
		    else ! current time is less than scene starting time, so add a day to current time
			    return ((the_time+TWENTY_FOUR_HOURS) - scene_started-->(sc-1))%(TWENTY_FOUR_HOURS);
	    2: return scene_started-->(sc-1);
	    3:
		    if (the_time >=scene_ended-->(sc-1)) ! current time is the same or later than scene ending time, so no change
			    return (the_time - scene_ended-->(sc-1))%(TWENTY_FOUR_HOURS);
		    else ! current time is less than scene ending time, so add a day to current time
			    return ((the_time+TWENTY_FOUR_HOURS) - scene_ended-->(sc-1))%(TWENTY_FOUR_HOURS);
	    4: return scene_ended-->(sc-1);
    }
];

-) instead of "Scene Questions" in "Time.i6t".
```

**Comment by zedlopez** [comment]
This is also adequate to fix the issue:

```
To decide which time is the time since (S - a scene) began:
  decide on time of day minus the time when S began.
```

**Comment by zedlopez** [comment]
reported as https://inform7.atlassian.net/browse/I7-2074
fixed by https://github.com/ganelson/inform/pull/109
