### ISSUE TITLE
Please add a compiler warning for ambiguous function definitions

### ISSUE THREAD

**Issue by selkieTG** [i7/inform7-bugs#17]
In general i7's rules for choosing the right function to use when you define another function of the same name but more specialised parameters works brilliantly. But when you define a function with multiple parameters and different levels of specialisations, you give it an impossible choice to decide, and it gives no warning of any ambiguity. It took me a day recently to work out why my function wasn't being called.
To make it clear, if I have
```
To compute some action on (T - a box) by (P - a person):
To compute some action on (T - a cube) by (P - a person):
To compute some action on (T - a box) by (P - a postman):
```
I wish the compiler could warn that it had been given an ambiguous choice, and which it selected.

**Comment by zedlopez** [comment]
reported https://inform7.atlassian.net/browse/I7-2386
