### ISSUE TITLE
Compiler generates wrong code when defining a "to decide" phrase without making a decision

### ISSUE THREAD

**Issue by awlck** [i7/inform7-bugs#2]
As discussed here: https://intfiction.org/t/unexpected-arithmetic-results-why/50495

When writing a "to decide" phrase for some block value type (e.g. text) but never using the "decide on ..." phrase, the compiler gets itself confused on the function arguments and generates nonsense code.

**Comment by zedlopez** [comment]
[I7-2069](https://inform7.atlassian.net/browse/I7-2069) in new tracker

**Comment by zedlopez** [comment]
[fixed in v10 commit 25cc80a0](https://github.com/ganelson/inform/commit/25cc80a011f1a8b780b6328c1a08daf75c034b78)
