### ISSUE TITLE
Referring via a plural form to multiple objects when that plural form has not been defined (e.g. ‘take flasks’ or ‘take 3 flasks’ when ‘flasks’ is not defined as a plural of flask) leads to inappropriate parser responses

### ISSUE THREAD

**Issue by curiousdannii** [i7/inform7-bugs#4]
Reported here: https://intfiction.org/t/rooms-is-actually-a-common-last-name/50922/14

**Comment by zedlopez** [comment]
reported https://inform7.atlassian.net/browse/I7-2070
fixed https://github.com/ganelson/inform/commit/13bbc6a2188ab965acddfd88ecd8d9c07b8f269c
