### ISSUE TITLE
For characters other than the player, objects that are not possessions remain in scope even in darkness

### ISSUE THREAD

**Issue by curiousdannii** [i7/inform7-bugs#5]
Reported here: https://intfiction.org/t/the-mysteries-of-aaron-reeds-remembering-extension-and-a-solution/49840/19

**Comment by zedlopez** [comment]
this has been fixed in v10 (tested with commit 62bfb9d45283cadeca8981e16ccbff6b2ff3d243)

**Comment by curiousdannii** [comment]
You can give a direct link :) https://github.com/ganelson/inform/commit/62bfb9d45283cadeca8981e16ccbff6b2ff3d243
