### ISSUE TITLE
Enterable supporters that are part of things cause weird behaviour

### ISSUE THREAD

**Issue by awlck** [i7/inform7-bugs#6]
Discussed here: https://intfiction.org/t/more-weirdness-with-enterable-supporters-that-are-part-of-things/45991

**Comment by zedlopez** [comment]
Other discussion in:
 https://intfiction.org/t/i7-extension-enterable-underside-first-version/47179/9
https://intfiction.org/t/dialog-style-object-hierarchy-doable/45977/5

**Comment by zedlopez** [comment]
reported as https://inform7.atlassian.net/browse/I7-1959
