### ISSUE TITLE
The showme command doesn't list correctly the contents of a container when it's part of something

### ISSUE THREAD

**Issue by floriancargoet** [i7/inform7-bugs#9]
The `showme` command doesn't list correctly the contents of a container when it's part of something.
In the following example, the left drawer contains some documents while the right one contains a banana. The `showme` output list the documents under the right drawer instead of the left one.

```
Test is a room.

A desk is a supporter in Test.
Left drawer and right drawer are containers part of the desk.
Some documents are in the left drawer.
A banana is in the right drawer.
```
**Actual ouput**
```
>showme desk
desk - supporter
    Left drawer (part of desk) - open container
    right drawer (part of desk) - open container
        banana
        documents
```
**Expected ouput**
```
>showme desk
desk - supporter
    Left drawer (part of desk) - open container
        documents
    right drawer (part of desk) - open container
        banana
```
### Fix

The bug comes from the I6 template routine `ShowMeRecursively` from `Tests.i6t`.
It iterates in this order:
1. component_child
2. obj.component_sibling
3. child(obj)
4. sibling(obj)

<details><summary>Code</summary>
<pre>
	if (obj.component_child) c = c | ShowMeRecursively(obj.component_child, depth+2, f);
	if ((depth>0) && (obj.component_sibling))
		c = c | ShowMeRecursively(obj.component_sibling, depth, f);
	if (child(obj)) c = c | ShowMeRecursively(child(obj), depth+2, f);
	if ((depth>0) && (sibling(obj))) c = c | ShowMeRecursively(sibling(obj), depth, f);
</pre>
</details>

If you swap 2 & 3, it prints the correct output: 
1. component_child
2. child(obj)
3. obj.component_sibling
4. sibling(obj)

<details><summary>Fixed code</summary>
<pre>
	if (obj.component_child) c = c | ShowMeRecursively(obj.component_child, depth+2, f);
	if (child(obj)) c = c | ShowMeRecursively(child(obj), depth+2, f);
	if ((depth>0) && (obj.component_sibling))
		c = c | ShowMeRecursively(obj.component_sibling, depth, f);
	if ((depth>0) && (sibling(obj))) c = c | ShowMeRecursively(sibling(obj), depth, f);
</pre>
</details>

**Comment by zedlopez** [comment]
pull request submitted: https://github.com/ganelson/inform/pull/51

**Comment by zedlopez** [comment]
fix has been incorporated in v10
